name: PR check Info

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  pr-check-info:

    runs-on: [self-hosted]
    worklow_dispatch:
      inputs:
        tag:
          description: 'Tag to check'
          required: true
          type: choice
          default: 'TC robot-ci-demo'
          options:
            - 'TC_robot-ci-demo'
            - 'TC_robotfw-learning'
        project_code:
          description: 'Project code to check'
          required: true
          type: choice
          default: 'robot-ci-demo'
          options:
            - 'PC_robot-ci-demo'
            - 'PC_robotfw-learning'

    permissions:
      contents: read
      pull-requests: write

    steps:

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Check PR info
          working-directory: ${{ github.workspace }}
          env:
            PYTHONPATH: ${{ github.workspace }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            if project_code == 'PC_robot-ci-demo':
                print("tag ${{ inputs.tag }} and project_code ${{ inputs.project_code }}")
            elif project_code == 'PC_robotfw-learning':
                print("tag ${{ inputs.tag }} and project_code ${{ inputs.project_code }}")