on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to check'
        required: true
        default: 'TC_robot-ci-demo'
        type: choice
        options:
          - TC_robot-ci-demo
          - TC_robotfw-learning

      project_code:
        description: 'Project code to check'
        required: true
        default: 'PC_robot-ci-demo'
        type: choice
        options:
          - PC_robot-ci-demo
          - PC_robotfw-learning

jobs:
  pr-check-info:
    runs-on: self-hosted

    steps:
      - name: Debug
        run: |
          Write-Host "project_code='${{ github.event.inputs.project_code }}'"
          Write-Host "tag='${{ github.event.inputs.tag }}'"

      - name: Check project
        run: |
          if ("${{ github.event.inputs.project_code }}" -eq "PC_robot-ci-demo") {
              Write-Host "Robot CI Demo selected"
              required_file = "robot_ci_demo.xlsx"
          }
          elseif ("${{ github.event.inputs.project_code }}" -eq "PC_robotfw-learning") {
              Write-Host "Robot FW Learning selected"
              required_file = "robotfw_learning.xlsx"
          }
      
          -name: Check tag
          run: |
            echo "required_file=${required_file}"