name: PR check Info

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  pr-check-info:

    runs-on: [self-hosted]

    steps:

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Check PR info
          working-directory: ${{ github.workspace }}
          env:
            PYTHONPATH: ${{ github.workspace }}
          run: |
            echo "current working directory: $(pwd)"
            python -c "import sys; print('Python executable:', sys.executable); print('Python path:'); print(*sys.path, sep='\n')"
            python -u scripts/check_pr_info.py    

            