name: Robot Framework Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  robot-tests:

    runs-on: [self-hosted]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Python
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run Robot tests
        run: |
          robot --outputdir results tests/

      - name: Upload Robot results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
