name: Robot Framework Tests

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  robot-tests:

    runs-on: [self-hosted]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Python
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run Robot tests
        run: |
          python -m robot --outputdir results tests/

      - name: Upload Robot results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/

      - name: Connect to AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1

      - name: Upload Robot results to S3
        if: always()
        run: |
          aws s3 cp results/report.html s3://mkmrobotop/report.html
          